import type { Config } from 'tailwindcss'
import typography from '@tailwindcss/typography'
import scrollbar from 'tailwind-scrollbar'

export default {
  content: ['./src/**/*.{astro,md,mdx,ts,tsx}'],
  theme: {
    fontFamily: {
      sans: [
        'Inter Variable',
        'Inter',
        '-apple-system',
        'HarmonyOS Sans SC',
        'MiSans',
        'Source Han Sans SC',
        'Noto Sans SC',
        'system-ui',
        'Roboto',
        'emoji',
        'sans-serif',
      ],
      serif: [
        'Source Han Serif SC',
        'Noto Serif SC',
        'Times',
        'Times New Roman',
        'Georgia',
        'emoji',
        'serif',
      ],
      mono: [
        'Cascadia Mono',
        'JetBrains Mono Variable',
        'JetBrains Mono',
        'Consolas',
        'Roboto Mono',
        'Fira Mono',
        'Courier New',
        '-apple-system',
        'HarmonyOS Sans SC',
        'MiSans',
        'Source Han Sans SC',
        'Noto Sans SC',
        'system-ui',
        'emoji',
        'monospace',
      ],
      emoji: [
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
        'emoji',
      ],
    },
    extend: {
      colors: {
        light: {
          50: '#f6f8fa',
          100: '#eaeef2',
          200: '#d0d7de',
          300: '#afb8c1',
          400: '#8c959f',
          500: '#6e7781',
          600: '#57606a',
          700: '#424a53',
          800: '#32383f',
          900: '#24292f',
          950: '#1f2328',
        },
        dark: {
          50: '#f0f6fc',
          100: '#c9d1d9',
          200: '#b1bac4',
          300: '#8b949e',
          400: '#6e7681',
          500: '#484f58',
          600: '#30363d',
          700: '#21262d',
          800: '#161b22',
          900: '#0d1117',
          950: '#010409',
        },
      },
    },
  },
  plugins: [typography, scrollbar],
} satisfies Config
